### ISSUE TITLE
No implementation found for method printFile on channel flutter_pdf_printer

### ISSUE THREAD

**Issue by daaniiieel** [cadaniel/flutter_pdf_printer#3]
Hey! 
When using this module, I get the following error:
`Unhandled Exception: MissingPluginException(No implementation found for method printFile on channel flutter_pdf_printer)
E/flutter (15166): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (15166): <asynchronous suspension>
E/flutter (15166): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (15166): #2      FlutterPdfPrinter.printFileFromBytes (package:flutter_pdf_printer/flutter_pdf_printer.dart:25:22)
E/flutter (15166): #3      FlutterPdfPrinter.printFile (package:flutter_pdf_printer/flutter_pdf_printer.dart:20:11)
E/flutter (15166): <asynchronous suspension>
E/flutter (15166): #4      _PageFrameState.build.<anonymous closure> (package:filcnaplo/ui/pages/frame.dart:181:41)
E/flutter (15166): <asynchronous suspension>
E/flutter (15166): #5      _PageFrameState.build.<anonymous closure> (package:filcnaplo/ui/pages/frame.dart)
E/flutter (15166): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter (15166): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter (15166): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (15166): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (15166): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (15166): #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter (15166): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter (15166): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter (15166): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (15166): #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (15166): #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (15166): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (15166): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:220:19)
E/flutter (15166): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
E/flutter (15166): #20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:263:11)
E/flutter (15166): #21     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:157:7)
E/flutter (15166): #22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:103:7)
E/flutter (15166): #23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:87:7)
E/flutter (15166): #24     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (15166): #25     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (15166): #26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (15166): #27     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (15166): #28     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
`

**Comment by u17zl** [comment]
@daaniiieel Hi, I met the same issue, after checking this issue on flutter 

https://github.com/flutter/flutter/issues/10912#issuecomment-310499594

Simply speaking, 

```
flutter clean
```

Hope it will work for you as well.
